---
title: "PyTorch Tutorial"
author: "Rafael Alcantara"
format:
  html:
    toc: true
editor: visual
---

# Quarto setup

In this section, we describe the steps to get Python and relevant libraries working in Quarto. If not running in Quarto, or if Quarto is already setup in your machine, skip to the next section.

If running on Windows, get miniconda [here](https://docs.anaconda.com/miniconda/)[^1].

[^1]: Might be necessary to choose the "install for all users" option; some useful resources for Windows include <https://stackoverflow.com/questions/59721699/anaconda-is-unable-to-create-process-on-windows10>, <https://stackoverflow.com/questions/60120763/r-reticulate-unable-to-locate-conda-environment-when-attempting-to-use-condae> and <https://stackoverflow.com/questions/35709497/anaconda-python-where-are-the-virtual-environments-stored>

-   Run in terminal (use Anaconda terminal if on Windows):

``` {style="color: green; background-color: lightgray"}
conda create -n PyTorch python=3.11 pytorch torchvision torchtext torchaudio -c pytorch
```

-   If eventually you need to add more packages to that environment, run in terminal:

``` {style="color: green; background-color: lightgray"}
conda activate PyTorch
pip3 install package (etc.)
```

-   Run this in R code block in the preamble:

```{r}
if (Sys.info()["sysname"]=="Windows")
  {
    reticulate::use_condaenv(condaenv = "C:\\Users\\Rafael Alcantara\\.conda\\envs\\PyTorch")
  } else
  {
    reticulate::use_condaenv(condaenv = "PyTorch")
  }
```

-   If you need to get the exact path for the conda environment (in case it's not in the path for R), do:

    ``` {style="color: green; background-color: lightgray"}
    conda activate PyTorch
    echo %CONDA_PREFIX% # (Windows)
    echo $CONDA_PREFIX
    ```

-   To check if everything works, run this in Python code block:

```{python}
import os, sys
os.path.dirname(sys.executable)
```

# Model setup

In this vignette, we will run the tutorial from <https://pytorch.org/tutorials/beginner/basics/intro.html> and add a hook that extracts the output from any given layer in the neural network.

First, we load the relevant libraries:

```{python}
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader
from torchvision import datasets
from torchvision.transforms import ToTensor
```

To download the train and test data for the tutorial, we use the `datasets` class from `torchvision`, which is a subclass of the general `Datasets` class from `torch.utils.data`. We will work with data from the Fashion-MNIST dataset, which consists of samples of 28x28 grayscale images and labels from a total of 10 classes.

```{python}
# Download training data from open datasets.
training_data = datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=ToTensor(),
)

# Download test data from open datasets.
test_data = datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=ToTensor(),
)
```

Then, we create data loaders for each data set. `DataLoader` is a class from `torch.utils.data` which \`\`**wraps an iterable around the `Dataset` to enable easy access to the samples**'' (from the [PyTorch tutorial on data classes](https://pytorch.org/tutorials/beginner/basics/data_tutorial.html); see [documentation](https://pytorch.org/docs/stable/data.html) for more details)[^2].

[^2]: For a pretty straightforward introduction to Python loops, iterators *etc.*, check <https://realpython.com/python-for-loop/>; basically, the loop internally does `iter(x)` to get the iterator, `next()` to move forward in the object *etc.*

```{python}
batch_size = 64

# Create data loaders.
train_dataloader = DataLoader(training_data, batch_size=batch_size)
test_dataloader = DataLoader(test_data, batch_size=batch_size)

for X, y in test_dataloader:
    print(f"Shape of X [N, C, H, W]: {X.shape}")
    print(f"Shape of y: {y.shape} {y.dtype}")
    break
```

Now, we determine the backend that will be used for training.

```{python}
# Get cpu, gpu or mps device for training.
device = (
    "cuda"
    if torch.cuda.is_available()
    else "mps"
    if torch.backends.mps.is_available()
    else "cpu"
)
print(f"Using {device} device")
```

We can now proceed to create a basic NN model. Each model is defined by a class which must be a subclass of `torch.nn.Module`, a loss function and an optimizer. We also define functions to train and test the model, and a hook that is registered to the model object after training, which extracts the output from a given layer.

## Model class

This model consists of 3 linear layers, with a ReLU activation function between each (in this case, the dimension of the output of the last layer, 10, must equal the number of classes)[^3].

[^3]: Check `nn.Module` [documentation](https://github.com/pytorch/pytorch/blob/c19c38469030cdf399714eb2051887f4583006a8/torch/nn/modules/module.py) for more details and a small example

```{python}
# Define model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork,self).__init__()
        self.flatten = nn.Flatten()
        self.l1 = nn.Linear(28*28, 512)
        self.l2 = nn.Linear(512, 512)
        self.l3 = nn.Linear(512, 10)

    def forward(self, x):
        x = self.flatten(x)
        x = self.l1(x)
        x = F.relu(x)
        x = self.l2(x)
        x = F.relu(x)
        x = self.l3(x)
        x = F.log_softmax(x,dim=1)
        return x

model = NeuralNetwork().to(device)
print(model)
```

## Loss function and optimizer

```{python}
loss_fn = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(model.parameters(), lr=1e-3)
```

## Train and test functions

```{python}
def train(dataloader, model, loss_fn, optimizer):
    size = len(dataloader.dataset)
    model.train() ## Get into training mode
    for batch, (X, y) in enumerate(dataloader):
        X, y = X.to(device), y.to(device)

        # Compute prediction error
        pred = model(X)
        loss = loss_fn(pred, y)

        # Backpropagation
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()

        if batch % 100 == 0:
            loss, current = loss.item(), (batch + 1) * len(X)
            print(f"loss: {loss:>7f}  [{current:>5d}/{size:>5d}]")
            
def test(dataloader, model, loss_fn):
    size = len(dataloader.dataset)
    num_batches = len(dataloader)
    model.eval() ## Tell it to not train the model again (go into evaluation mode)
    test_loss, correct = 0, 0
    with torch.no_grad(): ## Don't calculate gradients (since it's not training)
        for X, y in dataloader:
            X, y = X.to(device), y.to(device)
            pred = model(X)
            test_loss += loss_fn(pred, y).item()
            correct += (pred.argmax(1) == y).type(torch.float).sum().item()
    test_loss /= num_batches
    correct /= size
    print(f"Test Error: \n Accuracy: {(100*correct):>0.1f}%, Avg loss: {test_loss:>8f} \n")
```

## Hook for layer output

Add hook to extract a given layer [^4] [^5]:

[^4]: <https://www.geeksforgeeks.org/what-are-pytorch-hooks-and-how-are-they-applied-in-neural-network-layers/>

[^5]: <https://discuss.pytorch.org/t/how-can-l-load-my-best-model-as-a-feature-extractor-evaluator/17254/5>

```{python}
activation = {}

def get_activation(name):
  def hook(model,input,output):
    activation[name] = output.detach()
  return hook
```

The structure here is as follows. The hook function is structured as:

``` {style="color: green; background-color: lightgray"}
def hook(model,input,output):
  activation['layer'] = output.detach()
```

The outer function is just a wrapper to make it easier to extract any layer via the `name` parameter.

Important note: hooks only work after you register them. So, if you train the model, and then register the hook, the `activation` object will be empty. Only if you register the hook before you train the model, test it *etc.*, you can recover the layer.

# Model training and evaluation

We run the model for 5 epochs (after each epoch, we test the model to keep track of how it is improving):

```{python}
epochs = 5
for t in range(epochs):
    print(f"Epoch {t+1}\n-------------------------------")
    train(train_dataloader, model, loss_fn, optimizer)
    test(test_dataloader, model, loss_fn)
print("Done!")
```

Now that we've finished training the model, we register the hook to extract the last layer:

```{python}
model.l2.register_forward_hook(get_activation('l2'))
model.l3.register_forward_hook(get_activation('l3'))
```

If we want to save/load the model, run this:

```{python}
# torch.save(model.state_dict(), "model.pth")
# print("Saved PyTorch Model State to model.pth")
# model = NeuralNetwork().to(device)
# model.load_state_dict(torch.load("model.pth", weights_only=True))
```

We can check what the output from the last layer looks like:

```{python}
print(activation)
```

Finally, we can make predictions for new data points:

```{python}
classes = [
    "T-shirt/top",
    "Trouser",
    "Pullover",
    "Dress",
    "Coat",
    "Sandal",
    "Shirt",
    "Sneaker",
    "Bag",
    "Ankle boot",
]

model.eval()
x, y = test_data[0][0], test_data[0][1]
with torch.no_grad():
    x = x.to(device)
    pred = model(x)
    predicted, actual = classes[pred[0].argmax(0)], classes[y]
    print(f'Predicted: "{predicted}", Actual: "{actual}"')
    print(activation['l2'].shape)
    print(activation['l2'])
    print(activation['l3'].shape)
    print(activation['l3'])
```

# To do

Right now, I've only figured out how to get the layers per observation. If I evaluate the model with the whole test set, the layers are recovered per batch (if I understand it correctly), but if I do it per observation I can get the layers for each point. There probably is a more efficient way of doing this, but I haven't figured it out yet.
